# Generated by Django 4.2.3 on 2024-02-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_choice_question_delete_demotable_delete_prerak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
